### PR TITLE
Read printers generically

### PR DESCRIPTION
**Pull request by swflint**

### CODE REVIEW

**Comment by haji-ali** [comment]
I think the generic infix is interesting, but I doubt there would be much for its use. At least I don't see the point of generality without more use-cases than what we already have.

What is the benefit over using a simple reader as implemented by `transient`?

**Comment by swflint** [comment]
For example, in the `a2ps` transient, there are currently three places (and several more which I should probably implement) where I want to get option values from the command line just like is done for the printer.  Rather than repeat a bunch of code to run a command, split the lines, process it and then present the options to the user for completion, this simplifies it to specifying a command and and a filtering/processing step, that is, this makes the reader simpler.

**Comment by haji-ali** [comment]
I see. What do you think about something with dynamic options where the choices are obtained from a function (Note that it should be an option not a switch)?

```
(defclass transient-extras-dynamic-option (transient-option)
  ((choices-func :initarg :choices-func)
   (cache-choices-p :initarg :cachep :initform nil))
  "Class used for options with dynamic choices.")
```
The choices should be cached in `choices`. 

One would set the `choices-fun` to a some reader from a process (with filtering, async completing... or whatever).

**Comment by swflint** [comment]
What about a `transient-extras-dynamic-option` as shown and a `transient-extras-dynamic-option-from-command` which behaves similarly but contains the logic to read from a process.  Again, my concern is that I have to collect possible options from commando output in three plus places for a2ps, so reimplementation of initial read & complete potentially means that the interface may be subtly different between options, when a consistent interface would be better.

**Comment by haji-ali** [comment]
I agree with you about re-using code of course. One should indeed create a function that can be re-used as `choices-func` (or even better, a generic reader function like `transient-extras-lp--read-printer` that can be used in `reader`).

The point here is that I think a transient class is the wrong level at which to introduce such functionality. I prefer to use the functionality (and more importantly the interface) that already exists in `transient` as much as possible (which is why I ultimately prefer using `reader` rather than defining a new class). I believe creating a new class should be done when the functionality cannot be implemented in the current interface.

**Comment by swflint** [comment]
See, I'm seeing this as "this is an option where the choices are determined in a special manner with a fairly clear pattern".  I wonder if instead we consider using an `:around` method to collect choices and set the `choices` slot, then read/complete as normal?

**Comment by haji-ali** [comment]
Not sure what you mean by `:around` but I am really not questioning the usefulness of the class. I think it's really neat. 

However, here's how I would implement this functionality using the existing interface:

```lisp
(defun my/get-choices (command-line filter-function)
  (let* ((lines (split-string (with-temp-buffer
                                (apply #'call-process
                                       (first command-line)
                                       nil t nil
                                       (rest command-line))
                                (buffer-string))
                              "\n" 'omit-nulls)))
    (cl-remove-if #'null (mapcar filter-function lines))))

(defun my/reader (command-line
                  filter-function
                  prompt
                  initial-input history)
  (completing-read prompt
                   (my/get-choices command-line filter-function)
                   nil t
                   initial-input history))



(transient-define-infix printer-dynamic-choices ()
  :argument "--d"
  :key "d"
  :description "Dynamic"
  :class 'transient-option
  :reader (apply-partially 'my/reader '("lpstat" "-a") 'identity)
  :prompt "Printer (dynamic):")

(transient-define-infix printer-cached-choices ()
  :argument "--p"
  :key "p"
  :description "Cached"
  :class 'transient-option
  :choices (my/get-choices '("lpstat" "-a") 'identity)
  :prompt "Printer (cached):")

(transient-define-prefix printer-transient ()
  "Wave at the user"
  ["Options"
    (printer-dynamic-choices)
    (printer-cached-choices)])

(printer-transient)
```

**Comment by swflint** [comment]
Hopefully this commit makes it a bit better.

The generic option is still very much available, but this approach makes describing how the choices are collected a bit more obvious (i.e., run command with args, and filter).  My concern is that the overly generic approach requires a lot more boilerplate to implement.  It obviously doesn't have to, but I think that this makes it more clear what is going on with less context required.

**Comment by swflint** [comment]
How is this?  Now, there's no reason to override reader unless you need to do something special (and, afaict, even the :multiple option would work).

**Comment by haji-ali** [comment]
OK, to recap. This proposal is essentially:

```
(transient-define-argument transient-extras-lp--printer ()
  :class 'transient-extras-options-dynamic-choices
  :description "Printer"
  :key "d"
  :argument "-d"
  :cachep t
  :choices-function (transient-extras-get-options-from-command-output
                     "lpstat" '("-a")
                     (lambda (line)
                       (let ((index (string-match "[[:space:]]" line)))
                         (if index
                             (substring line nil index)
                           line))))
  :prompt "Printer? ")
```
instead of 
```
(transient-define-argument transient-extras-lp--printer ()
  :class 'transient-options
  :description "Printer"
  :key "d"
  :argument "-d"
  :choices (transient-extras-options-from-command-output
                     '("lpstat" "-a")
                     (lambda (line)
                       (let ((index (string-match "[[:space:]]" line)))
                         (if index
                             (substring line nil index)
                           line))))
  :prompt "Printer? ")
```
where `transient-extras-options-from-command-output` is `my/get-choices` from before.

I don't think there is any functionality lost with the second solution (if choices are dynamic, specifying a reader would also work). I will close this for now but I am happy to revisit it if we find that there is some missing functionality that the proposed solution provides.

**Comment by swflint** [comment]
This proposal doesn't provide missing functionality, but instead, it tries to leave the existing `choices` are separate from `reader` abstraction intact.  Since specifying `choices` in normal `transient-option` or `transient-switches` is separate from reading the choice, even with dynamic choices, this difference can and should remain.

This continues on in that style.  The choices are now specified by evaluating a `choices-function`, and reading can be further specialized as necessary, but the existing `transient-infix-read` can be used without requiring implementing a special reader for every different thing which needs choices determined dynamically, even if that reader is just a closure (significantly improving code reuse).  This means that modifying the behavior of reading an option happens in the same way as for other `transient-option` instances, which, among other things, could simplify transition from the old `transient-option` to this if it becomes necessary.

**Pull request closed without merging**
