### PR TITLE
WIP: Start implementation of a transient interface to pdftk

### PR DESCRIPTION
**Pull request by swflint**
My goal is to implement a transient interface to the `pdftk` PDF manipulation package.

This is still a draft (need to figure out how to do sub-transients for operations), but I hope it should be complete soon.

Once I figure out how to do sub-transients, I should be able to get the transient for find completed as well.

### CODE REVIEW

**Comment by swflint** [comment]
As it happens, sub-transients aren't necessary for this, so I'm going to un-draft this.

**Comment by haji-ali** [comment]
Thanks! I'll look into this over the weekend.

One quick note is that pdftk is incredibly complex with its inputs and doing a transient menu for it will be difficult. 
For example, your implementation doesn't seem to support selecting multiple files (including with handles). Also, `cat` can accept rotating pages per page, which this doesn't seem to support, right?

**Comment by swflint** [comment]
The handling of multiple files is something we don't support well to begin with.  I'd like to try and figure out a good way to handle that, but I'm just not sure if one exists (at the moment).  I suspect what's needed is a better file-list infix, but I need to read more in depth as to how that might be constructed.

Cat supports it passively.  As with most of the arguments, it currently just prompts for a string with no information about the format.  If we wanted to better support it, I'd likely need to sit down and write up a better "page range" infix, but given its complexity, I'm similarly not positive as to how best to do it.

It is still only basic support, but being able to call it from within PDF tools will be nice.

**Comment by swflint** [comment]
I'm going take this back to WIP.  I'd like to a) add a "password" option type, and b) include a patch to the README.

**Comment by swflint** [comment]
I think it makes sense for this to be blocked by #17.

**Comment by swflint** [comment]
This needs a fair bit of cleanup before it's usable.  Therefore, I'm closing it for now.

**Pull request closed without merging**
